"""Generate paper/numbers.tex and paper/table*.tex from results/.

No number in the paper is typed by hand. Every value is a macro \\ck{name}
that prints the value as a hyperlink to the exact line of the committed
results file, at the pinned tag TAG (never `main`).

  python scripts/make_numbers.py [TAG]      default TAG: v1.0
"""
from __future__ import annotations

import csv
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
RES = os.path.join(ROOT, "results")
PAPER = os.path.join(ROOT, "paper")
REPO_URL = "https://github.com/mark124/cache-key-soundness"
SOURCES = [("h", "results/headline.json"), ("t3", "results/table3_summary.json"),
           ("rq3", "results/rq3_summary.json"), ("t4", "results/table4_summary.json"),
           ("t5", "results/table5_summary.json"), ("t5r1", "results/table5_round1_summary.json")]


def tex_escape(s: str) -> str:
    return (str(s).replace("\\", r"\textbackslash{}").replace("_", r"\_").replace("%", r"\%")
            .replace("&", r"\&").replace("#", r"\#").replace("$", r"\$").replace("{", r"\{")
            .replace("}", r"\}").replace("~", r"\textasciitilde{}").replace("^", r"\^{}"))


def fmt(v):
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}".replace(",", "{,}")
    if isinstance(v, float):
        return f"{v:.1f}"
    return tex_escape(v)


def link(tag, rel, line, text):
    anchor = rf"\#L{line}" if line else ""   # \# : a bare # breaks \def
    return r"\href{%s/blob/%s/%s%s}{%s}" % (REPO_URL, tag, rel, anchor, text)


def numbers(tag):
    out = [r"% generated by scripts/make_numbers.py -- do not edit",
           r"\providecommand{\ck}[1]{\ifcsname ck@#1\endcsname\csname ck@#1\endcsname"
           r"\else\textbf{\textcolor{red}{??\detokenize{#1}}}\fi}",
           r"\newcommand{\repourl}{\url{%s}}" % REPO_URL,
           r"\newcommand{\repotag}{%s}" % tag]
    for prefix, rel in SOURCES:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        lines = open(path, encoding="utf-8").read().splitlines()
        data = json.load(open(path, encoding="utf-8"))
        for k, v in data.items():
            ln = next((i + 1 for i, l in enumerate(lines) if l.strip().startswith(f'"{k}"')), None)
            name = f"{prefix}.{k}"
            out.append(r"\expandafter\def\csname ck@%s\endcsname{%s}" % (name, link(tag, rel, ln, fmt(v))))
    with open(os.path.join(PAPER, "numbers.tex"), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


def csv_table(tag, rel, cols, headers, out_name, where=None, align=None):
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return
    rows = list(csv.DictReader(open(path, encoding="utf-8")))
    body = []
    for i, r in enumerate(rows):
        if where and not where(r):
            continue
        cells = []
        for c in cols:
            v = r[c]
            try:
                v = int(v)
            except ValueError:
                try:
                    v = float(v)
                except ValueError:
                    pass
            cells.append(fmt(v))
        # link the first cell of each row to its CSV line (header is line 1)
        cells[0] = link(tag, rel, i + 2, cells[0])
        body.append(" & ".join(cells) + r" \\")
    tex = [r"% generated by scripts/make_numbers.py from " + rel,
           r"\begin{tabular}{" + (align or "l" + "r" * (len(cols) - 1)) + "}", r"\toprule",
           " & ".join(headers) + r" \\", r"\midrule"] + body + [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(PAPER, out_name), "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(tex) + "\n")


def main():
    tag = sys.argv[1] if len(sys.argv) > 1 else "v1.0"
    os.makedirs(PAPER, exist_ok=True)
    numbers(tag)
    csv_table(tag, "results/table1_sample.csv",
              ["stars", "sampled", "retrieved", "with_workflows", "with_actions_cache",
               "caching_built_python_env", "pct_of_workflow_repos_caching_built_env"],
              ["Stars", "Sampled", "Retrieved", "Workflows", "Any cache", "Built env", r"\% of wf."],
              "table1.tex")
    csv_table(tag, "results/table2_key_composition.csv",
              ["verdict", "steps", "pct_steps", "with_skip_on_hit", "with_deps_hash", "with_os_signal",
               "restore_keys_drop_interpreter"],
              ["Key verdict", "Steps", r"\%", "Skip on hit", "Deps hashed", "OS in key", "Unsafe fallback"],
              "table2.tex")
    csv_table(tag, "results/table4_bench.csv",
              ["tool", "mode", "median_s", "min_s", "max_s"],
              ["Tool", "Strategy", "Median (s)", "Min (s)", "Max (s)"], "table4.tex",
              align="llrrr")
    csv_table(tag, "results/table3_matrix.csv",
              ["condition", "pip", "poetry", "uv"], ["Condition", "pip", "Poetry", "uv"], "table3.tex",
              align="llll")
    print("wrote paper/numbers.tex and tables")


if __name__ == "__main__":
    main()
